# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robin Janssens
author: Robin Janssens
email: contact@janssens.me.uk
description: > # this means to ignore newlines until "baseurl:"
  London based recent Computer Science MEng graduate and full-stack 
  engineer. Currently specialising in Node.js and AngularJS web application
  development. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robin.pm" # the base hostname & protocol for your site
twitter_username: rjanssens
github_username:  robinj
linkedin_username: robinjanssens
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
